comment: false

coverage:
  range: 0..100
  round: up
  precision: 0

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
